version: '3.7'
services: 
  db:
    build: .
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: helicoir
      MYSQL_DATABASE: develop